services:
  web:
    build: ./apps/web
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - photoapp-network

  server:
    build: ./apps/server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/photoapp
      STORAGE_TYPE: local
      LOCAL_MEDIA_PATH: /media
      # Ensure these match the DB service
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: photoapp
      PORT: 5000
    volumes:
      - media:/media
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - photoapp-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photoapp
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      # Automatically initialize the schema
      - ./apps/server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - photoapp-network

volumes:
  dbdata:
  media:


networks:
  photoapp-network:
    driver: bridge
