version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photoapp
    volumes:
      - dbdata:/var/lib/postgresql/data
  server:
    build: ./server
    depends_on: [db]
    environment:
      PORT: 5000
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: photoapp
      STORAGE_TYPE: local
      LOCAL_MEDIA_PATH: /app/media
      JWT_SECRET: 55f2b35553327ef6fa0a4518bcda0065795d5595d8d4f91ad4d6d52ef7ae16ab
    volumes:
      - media_storage:/app/media

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on: [server]

volumes:
  dbdata:
  media_storage:
