version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photoapp
    volumes:
      - dbdata:/var/lib/postgresql/data
  server:
    build: ../../apps/server
    networks:
      - photoapp-network
    environment:
      PORT: 5000
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: photoapp
      STORAGE_TYPE: local
      LOCAL_MEDIA_PATH: /app/media
      JWT_SECRET: 55f2b35553327ef6fa0a4518bcda0065795d5595d8d4f91ad4d6d52ef7ae16ab
    ports:
      - "5000:5000"
    volumes:
      - media_storage:/app/media

  client:
    build: ../../apps/web
    networks:
      - photoapp-network
    ports:
      - "3000:3000"

volumes:
  dbdata:
  media_storage:

networks:
  photoapp-network:
